### ISSUE TITLE
Predefined types are not allowed in calls to size()

### ISSUE THREAD

**Issue by dnewhall** [CordyJ/Open-TuringPlus#10]
I'm a bit surprised to see that this doesn't work:

```
put size(int)

Line 1 of malloctest.t: Syntax error at ')'  -  '@' expected
```

But this works:

```
type _int : int
put size(_int)
```

I suppose you can work around it, but it prevents things like `startOfBlock + (size(int1) * offset)`

**Comment by CordyJ** [comment]
Yes, that's true, ```size()``` is an attribute of a ```namedType``` in Turing.  A ```standardType``` is not ```namedType```.
